# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('woeid', models.CharField(max_length=16, unique=True)),
                ('longitude', models.CharField(max_length=32)),
                ('latitude', models.CharField(max_length=32)),
                ('parent_id', models.CharField(blank=True, max_length=16, null=True)),
                ('dtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Placetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'db_table': 'placetype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('volume', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'trend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrendModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PointField()),
                ('name', models.TextField()),
            ],
        ),
    ]
